### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by snth** [tobilg/duckerd#1]
Thank you for creating this! Looking forward to trying it out.

Just one comment on the name, I see where you are coming from with **Duck**DB **ER** **D**iagrams but in the Linux world it's common for things ending in d to be daemons. Of course it doesn't hold for all things (like `find`) but that was my first reaction upon seeing the name. I don't have a suggestion for anything better but it might be something to consider.

Thanks again.

**Comment by cdiaz** [comment]
Hi @snth, You're absolutely right about the “d” often being associated with daemons in the Linux world. In this case, though, “ERD” refers to "Entity-Relationship Diagram," a term common in database design to illustrate data structure

**Comment by tobilg** [comment]
As you and @cdiaz said, it's a combination of "Duck" for DuckDB, and "ERD" for Entity Relationship Diagram. I like the name, and keeping it as-is. Thanks for the feedback @snth.
